---
- name: create oozie group
  group: name=oozie state=present
  tags:
  - cdh5-base
  - cdh5-oozie
  - cdh5-oozie-user
  - cdh5-luancher
  
- name: create oozie user
  user: name=oozie group=oozie createhome=yes state=present
  tags:
  - cdh5-base
  - cdh5-oozie
  - cdh5-oozie-user
  - cdh5-luancher

- name: create .ssh directory for oozie user
  file: path=/home/oozie/.ssh state=directory owner=oozie group=oozie mode=0700
  tags:
  - cdh5-base
  - cdh5-oozie
  - cdh5-oozie-user
  - cdh5-luancher
