---
- name: install namenode pkgs
  yum: name={{ item }}-{{ version['hadoop'] }} state=present
  with_items:
  - hadoop-hdfs-namenode
  - hadoop-hdfs-zkfc
  tags:
  - cdh5-namenode
  - cdh5-namenode-primary


- name: create the data directory for the namenode metadata
  file: path={{ item }} state=directory owner=hdfs group=hdfs mode=0700
  with_items: 
  - /var/hadoop/data/1/
  - /var/hadoop/data/1/dfs/
  - /var/hadoop/data/2/
  - /var/hadoop/data/2/dfs/
  - /var/hadoop/data/1/dfs/nn/
  - /var/hadoop/data/2/dfs/nn
  #- "{{ dfs_namenode_name_dir }}"
  tags: 
  - cdh5-namenode
  - cdh5-namenode-primary

- name: create the dfs hosts exclude file
  file: path={{dfs_hosts_exclude}} state=touch  owner=hdfs group=hdfs mode=0644
  tags:
  - create-file
  - cdh5-namenode
  - cdh5-namenode-primary

- name: format the namenode
  shell: creates={{ item }} sudo -u hdfs hadoop namenode -format && touch {{ item }}
  with_items:
  - /var/hadoop/.status/namenode.formatted
  tags:
  - cdh5-namenode
  - cdh5-namenode-primary

- name: start hadoop namenode services
  service: name={{ item }} state=started
  with_items:
  - hadoop-hdfs-namenode
  tags:
  - cdh5-namenode
  - cdh5-namenode-primary
