#!/bin/sh
#$1=busdev-hadoop-bigdata
ROLE_NAME="busdev-hadoop-bigdata"

function get_key_id()
{

        ROLE_URL="curl http://169.254.169.254/latest/meta-data/iam/security-credentials/"$ROLE_NAME
        ctx=`curl http://169.254.169.254/latest/meta-data/iam/security-credentials/$ROLE_NAME`
        AccessKeyId=`echo $ctx |jq '.AccessKeyId'|awk -F'"' '{print $2}'`
        SecretAccessKey=`echo $ctx |jq '.SecretAccessKey'|awk -F'"' '{print $2}'`
}


function core_site_ck()
{
        grep $3  $2
        if [ "$?" -ne "0" ];then
                sed -i "s#${1}#${3}#g"  $2
        fi
}


function  main()
{
        core_site_file="/etc/hadoop/conf/core-site.xml"
        check_id_default="jason_s3_id"
        check_key_default="jason_s3_key"

        get_key_id
        core_site_ck $check_id_default  $core_site_file  $AccessKeyId
        core_site_ck $check_key_default  $core_site_file  $SecretAccessKey
}

main
